// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"encoding/json"
	"time"
)

type CartItem struct {
	ID        string `json:"id"`
	CartID    string `json:"cart_id"`
	ProductID string `json:"product_id"`
	Quantity  int64  `json:"quantity"`
}

type CategoriesWithProduct struct {
	ID       string          `json:"id"`
	Name     string          `json:"name"`
	Products json.RawMessage `json:"products"`
}

type Category struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Order struct {
	ID            string    `json:"id"`
	UserID        string    `json:"user_id"`
	PaymentMethod string    `json:"payment_method"`
	TotalCost     int64     `json:"total_cost"`
	OrderDate     time.Time `json:"order_date"`
}

type OrderItem struct {
	ID              string `json:"id"`
	OrderID         string `json:"order_id"`
	ProductID       string `json:"product_id"`
	Quantity        int64  `json:"quantity"`
	PriceAtPurchase int64  `json:"price_at_purchase"`
}

type Product struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Price       int64     `json:"price"`
	CategoryID  string    `json:"category_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ShoppingCart struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type ShoppingCartWithCartItem struct {
	ID        string          `json:"id"`
	UserID    string          `json:"user_id"`
	CreatedAt time.Time       `json:"created_at"`
	CartItems json.RawMessage `json:"cart_items"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}

type UsersWithProduct struct {
	Username          string          `json:"username"`
	HashedPassword    string          `json:"hashed_password"`
	FullName          string          `json:"full_name"`
	Email             string          `json:"email"`
	PasswordChangedAt time.Time       `json:"password_changed_at"`
	CreatedAt         time.Time       `json:"created_at"`
	Products          json.RawMessage `json:"products"`
}
