// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, id string) error
	DeleteProduct(ctx context.Context, id string) error
	GetCategory(ctx context.Context, id string) (CategoriesWithProduct, error)
	GetProduct(ctx context.Context, id string) (GetProductRow, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUserWithProducts(ctx context.Context, username string) (UsersWithProduct, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]CategoriesWithProduct, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
