apiVersion: v1
kind: Service
metadata:
  name: synapsis-challenge-api-service
spec:
  selector:
    # app.kubernetes.io/name: MyApp
    app: synapsis-challenge-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
